apiVersion: apps/v1
kind: Deployment
metadata:
  name: sac-k8-deployment
  labels:
    app: unshorten-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unshorten-api
  template: 
    metadata:
      labels:
        app: unshorten-api
    spec:
      automountServiceAccountToken: true
      containers:
      - name: unshorten-api-container
        image: "jmbmxer/link-unshorten:0.1"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /api
          name: unshorten-volume
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
      volumes:
        - name: unshorten-volume
          hostPath:
            path: /var/lib/google
            type: Directory
