apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sac-k8-deployments
  namespace: default
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io